apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: story-builder-data
  namespace: story-builder
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
